apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: {{ .Values.config.app.replicas }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.config.app.image.repository }}:{{ .Values.config.app.image.tag }}"
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: {{ .Values.config.app.resources.limits.cpu }}
              memory: {{ .Values.config.app.resources.limits.memory }}
            requests:
              cpu: {{ .Values.config.app.resources.requests.cpu }}
              memory: {{ .Values.config.app.resources.requests.memory }}
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: {{ .Values.config.app.service.type }}
  ports:
    - port: {{ .Values.config.app.service.port }}
      targetPort: 8080
      nodePort: {{ .Values.config.app.service.nodePort }}
  selector:
    app: backend