# ./backend/Dockerfile.dev
FROM node:22.9.0-slim

WORKDIR /usr/src/app

# No necesitamos COPY porque montamos todo el directorio como volumen
# Solo instalamos las dependencias
RUN mkdir -p /usr/src/app/node_modules && chown -R node:node /usr/src/app

USER node

EXPOSE 8080

CMD ["npm", "run", "dev"]