version: '3.8'

services:
  db:
    image: ghcr.io/${{ env.GITHUB_REPOSITORY_OWNER }}/demo:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=eG4clXnlGm
      - POSTGRES_DB=datos
      - POSTGRES_INITDB_ARGS="--encoding=UTF8"
    ports:
      - "30900:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d datos"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  backend:
    image: ghcr.io/${{ env.GITHUB_REPOSITORY_OWNER }}/demo:latest
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - HOST=0.0.0.0
      - CORS_ORIGIN=https://${{ env.GITHUB_REPOSITORY_OWNER }}.github.io/${{ env.GITHUB_REPOSITORY }}
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=eG4clXnlGm
      - DB_NAME=datos
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

volumes:
  postgres_data:
    driver: local

networks:
  app-network:
    driver: bridge