postgresql:
  enabled: true
  metrics: 
    enabled: true
  service:
    type: NodePort
    nodePorts:
      postgresql: 30100
  primary:
    persistence:
      enabled: true
      size: 4Gi
  readReplicas:
    replicaCount: 1
    persistence:
      enabled: true
      size: 4Gi

redis:
  enabled: true
  metrics:
    enabled: true
  service:
    type: NodePort
    nodePorts:
      redis: 30102
  architecture: replication
  master:
    persistence:
      enabled: true
      size: 4Gi
  replica:
    replicaCount: 1
    persistence:
      enabled: true
      size: 4Gi