# Archivo: .github/workflows/deploy.yml

name: "Docker Compose Deployment"

on:
  push:
    branches: [ "deployment" ]
    paths: [ "proyecto/caso5/demo/**" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push database
        uses: docker/build-push-action@v5
        with:
          context: ./proyecto/caso5/demo/database
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/demo-db:latest

      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: ./proyecto/caso5/demo/backend
          file: ./proyecto/caso5/demo/backend/Dockerfile.dev
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/demo-backend:latest

      - name: Update compose file
        run: |
          cd proyecto/caso5/demo
          sed -i 's|build:|image: ghcr.io/${{ github.repository_owner }}/demo-db:latest|g' docker-compose.yml
          sed -i 's|dockerfile: Dockerfile.dev|image: ghcr.io/${{ github.repository_owner }}/demo-backend:latest|g' docker-compose.yml

      - name: Deploy with Docker Compose
        run: |
          cd proyecto/caso5/demo
          docker compose pull
          docker compose up -d