name: "Deploy Backend and Database to GitHub Pages"
on:
  push:
    branches: [ "deployment" ]

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write 
      pages: write
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./proyecto/caso5/demo/docker-compose.prod.yml
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/demo:latest

    - name: Create static content
      run: |
        mkdir -p _site
        cat > _site/index.html << 'EOF'
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <title>API Documentation</title>
            <style>
                /* ... (content omitted for brevity) ... */
            </style>
        </head>
        <body>
            <div class="container">
                <h1>API Documentation</h1>
                <p>Click below to view the Swagger documentation for this API.</p>
                <a href="http://localhost:8080" class="button" id="redirectButton">View API Documentation</a>
            </div>

            <script>
                document.getElementById('redirectButton').href = window.location.hostname === 'localhost' 
                    ? 'http://localhost:8080' 
                    : 'https://${{ github.repository_owner }}.github.io/${{ github.repository }}/';
            </script>
        </body>
        </html>
        EOF

    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: _site

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2