# Archivo: .github/workflows/environment.yml

name: "Production Environment"
on: 
  push:
    branches: [ "deployment" ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment
        run: echo "Setting up production environment"